version: '3'

services:
  app:
    image: 'restaurantes-api:dev'
    build:
      context: .
    container_name: restaurantes-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/restaurante
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SRPING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: 'mysql:latest'
    container_name: 'database'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_DB=restaurante